apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend
    # 디폴트로 설정되는 ClusterIP도 내부에서 로드 밸런싱이 가능하다(외부로의 노출은 당연히 안된다.)
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80