apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      labels:
        app: users
    spec:
      containers:
        - name: users
          image: wnsvy607/kub-demo-users:latest
          env:
            - name: AUTH_ADDRESS
              # 수동으로 가져온 호스트 주소
              # value: "10.102.66.87"
              value: "auth-service.default"